Repository team-kosa-skynet/Morningstar-back, pull requests merged in 2025-07, with the labels that each got.

#4 Fix : gitignore
  .gitignore
  src/main/resources/application.yml
Labels: fix

#5 feat : 공통 ResponseDTO 수정
  src/main/java/com/gaebang/backend/global/util/ResponseDTO.java
Labels: feat, fix

#11 feat: 커뮤니티 API 시스템 구현
  src/main/java/com/gaebang/backend/domain/community/controller/.gitkeep
  src/main/java/com/gaebang/backend/domain/community/controller/BoardController.java
  src/main/java/com/gaebang/backend/domain/community/controller/BoardLikeController.java
  src/main/java/com/gaebang/backend/domain/community/controller/CommentController.java
  src/main/java/com/gaebang/backend/domain/community/dto/reqeust/BoardCreateAndEditRequestDto.java
  src/main/java/com/gaebang/backend/domain/community/dto/reqeust/CommentRequestDto.java
  src/main/java/com/gaebang/backend/domain/community/dto/reqeust/SearchConditionRequestDto.java
  src/main/java/com/gaebang/backend/domain/community/dto/response/BoardDetailResponseDto.java
  src/main/java/com/gaebang/backend/domain/community/dto/response/BoardLikeResponseDto.java
  src/main/java/com/gaebang/backend/domain/community/dto/response/BoardListResponseDto.java
  src/main/java/com/gaebang/backend/domain/community/dto/response/CommentResponseDto.java
  src/main/java/com/gaebang/backend/domain/community/entity/.gitkeep
  src/main/java/com/gaebang/backend/domain/community/entity/Board.java
  src/main/java/com/gaebang/backend/domain/community/entity/BoardLike.java
  src/main/java/com/gaebang/backend/domain/community/entity/BoardReport.java
  src/main/java/com/gaebang/backend/domain/community/entity/Comment.java
  src/main/java/com/gaebang/backend/domain/community/entity/CommentReport.java
  src/main/java/com/gaebang/backend/domain/community/entity/Image.java
  src/main/java/com/gaebang/backend/domain/community/exception/BoardNotFoundException.java
  src/main/java/com/gaebang/backend/domain/community/exception/CommentNotFoundException.java
  src/main/java/com/gaebang/backend/domain/community/repository/.gitkeep
  src/main/java/com/gaebang/backend/domain/community/repository/BoardLikeRepository.java
  src/main/java/com/gaebang/backend/domain/community/repository/BoardReportRepository.java
  src/main/java/com/gaebang/backend/domain/community/repository/BoardRepository.java
  src/main/java/com/gaebang/backend/domain/community/repository/CommentReportRepository.java
  src/main/java/com/gaebang/backend/domain/community/repository/CommentRepository.java
  src/main/java/com/gaebang/backend/domain/community/repository/ImageRepository.java
  src/main/java/com/gaebang/backend/domain/community/repository/LikeRepository.java
  src/main/java/com/gaebang/backend/domain/community/service/.gitkeep
  src/main/java/com/gaebang/backend/domain/community/service/BoardLikeService.java
  src/main/java/com/gaebang/backend/domain/community/service/BoardService.java
  src/main/java/com/gaebang/backend/domain/community/service/CommentService.java
  src/main/java/com/gaebang/backend/domain/community/util/TimeUtil.java
  src/main/java/com/gaebang/backend/global/exception/ErrorCode.java
Labels: feat

#12 fix: Community API DTO 타입 불일치 및 FETCH JOIN 오류 해결
  src/main/java/com/gaebang/backend/domain/community/dto/response/BoardListProjectionDto.java
  src/main/java/com/gaebang/backend/domain/community/dto/response/BoardListResponseDto.java
  src/main/java/com/gaebang/backend/domain/community/repository/BoardRepository.java
  src/main/java/com/gaebang/backend/domain/community/service/BoardService.java
  src/test/java/com/morningstar/backend/http/community/.gitkeep
Labels: fix

#13 feat : 내정보 조회 및 이메일 확인 기능 추가
  src/main/java/com/gaebang/backend/domain/member/controller/MemberController.java
  src/main/java/com/gaebang/backend/domain/member/dto/response/GetUserResponseDto.java
  src/main/java/com/gaebang/backend/domain/member/service/MemberService.java
  src/test/java/com/morningstar/backend/http/member/crudMember.http
Labels: feat

#16 fix: Community API DTO 타입 불일치 및 데이터 구조 수정
  src/main/java/com/gaebang/backend/domain/community/controller/BoardController.java
  src/main/java/com/gaebang/backend/domain/community/controller/BoardLikeController.java
  src/main/java/com/gaebang/backend/domain/community/dto/response/BoardDetailResponseDto.java
  src/main/java/com/gaebang/backend/domain/community/entity/Board.java
  src/main/java/com/gaebang/backend/domain/community/repository/BoardRepository.java
  src/main/java/com/gaebang/backend/domain/community/service/BoardService.java
Labels: fix

#21 feat: 게시판 신고 기능 구현
  src/main/java/com/gaebang/backend/domain/community/controller/BoardReportController.java
  src/main/java/com/gaebang/backend/domain/community/dto/reqeust/BoardReportRequestDto.java
  src/main/java/com/gaebang/backend/domain/community/dto/response/BoardReportResponseDto.java
  src/main/java/com/gaebang/backend/domain/community/exception/BoardReportNotFoundException.java
  src/main/java/com/gaebang/backend/domain/community/exception/DuplicateReportException.java
  src/main/java/com/gaebang/backend/domain/community/repository/BoardReportRepository.java
  src/main/java/com/gaebang/backend/domain/community/service/BoardReportService.java
  src/main/java/com/gaebang/backend/global/exception/ErrorCode.java
Labels: feat

#23 feat: 게시글 조회 API에 멤버 레벨 정보 포함 및 비 로그인 시 게시글 조회 가능하게 변경
  src/main/java/com/gaebang/backend/domain/community/controller/BoardController.java
  src/main/java/com/gaebang/backend/domain/community/dto/response/BoardListProjectionDto.java
  src/main/java/com/gaebang/backend/domain/community/dto/response/BoardListResponseDto.java
  src/main/java/com/gaebang/backend/domain/community/repository/BoardRepository.java
  src/main/java/com/gaebang/backend/domain/community/service/BoardService.java
  src/main/java/com/gaebang/backend/domain/member/service/MemberService.java
  src/main/java/com/gaebang/backend/global/springsecurity/SpringSecurityConfig.java
Labels: feat

#24 feat : 닉네임 중복확인 api, 현재 비밀번호 확인 api 추가
  src/main/java/com/gaebang/backend/domain/member/controller/MemberController.java
  src/main/java/com/gaebang/backend/domain/member/dto/request/CheckPasswordRequestDto.java
  src/main/java/com/gaebang/backend/domain/member/service/MemberService.java
  src/main/java/com/gaebang/backend/global/springsecurity/OAuth2LoginSuccessHandler.java
  src/main/java/com/gaebang/backend/global/springsecurity/SpringSecurityConfig.java
  src/main/resources/application-core.yml
  src/test/java/com/morningstar/backend/http/member/crudMember.http
Labels: feat

#25 fix: BoardListProjectionDto에서 필드 순서 변경
  src/main/java/com/gaebang/backend/domain/community/controller/BoardReportController.java
  src/main/java/com/gaebang/backend/domain/community/dto/response/BoardListProjectionDto.java
  src/main/java/com/gaebang/backend/domain/community/dto/response/BoardListResponseDto.java
  src/main/java/com/gaebang/backend/domain/community/service/BoardService.java
Labels: fix

#26 feat: 게시글, 댓글 생성 시 포인트 지급 로직 추가
  src/main/java/com/gaebang/backend/domain/community/service/BoardService.java
  src/main/java/com/gaebang/backend/domain/community/service/CommentService.java
  src/main/java/com/gaebang/backend/domain/point/entity/PointType.java
Labels: feat

#29 hotfix : cors 설정 추가
  src/main/java/com/gaebang/backend/global/springsecurity/OAuth2LoginSuccessHandler.java
  src/main/java/com/gaebang/backend/global/springsecurity/SpringSecurityConfig.java
Labels: fix
