Repository team-kosa-skynet/Morningstar-back, pull requests merged in 2025-08, with the labels that each got.

#46 feat : 깃허브 액션 cicd 적용
  .github/workflows/gradle.yml
Labels: fix

#48 fix : 깃허브 액션 cicd 적용
  .github/workflows/gradle.yml
Labels: fix

#51 fix : 깃허브 액션 cicd 수정
  .github/workflows/gradle.yml
Labels: fix

#52 fix : 깃허브 액션 cicd 수정
  .github/workflows/gradle.yml
Labels: fix

#77 refactor : AI 추천 관련 기능 수정
  src/main/java/com/gaebang/backend/domain/aianalysis/controller/RecommendationController.java
  src/main/java/com/gaebang/backend/domain/aianalysis/recommendation/Model.java
  src/main/java/com/gaebang/backend/domain/aianalysis/recommendation/ModelScoreCalculator.java
  src/main/java/com/gaebang/backend/domain/aianalysis/service/RecommendationService.java
  src/test/java/com/morningstar/backend/http/AI/analysis.http
Labels: refactor

#80 feat : AI 기자 뉴스기능 업데이트
  build.gradle
  src/main/java/com/gaebang/backend/domain/ai/controller/AIAnalysisController.java
  src/main/java/com/gaebang/backend/domain/ai/controller/AiNewsController.java
  src/main/java/com/gaebang/backend/domain/ai/controller/AiUpdatesController.java
  src/main/java/com/gaebang/backend/domain/ai/controller/RecommendationController.java
  src/main/java/com/gaebang/backend/domain/ai/dto/AIAnalysisDto.java
  src/main/java/com/gaebang/backend/domain/ai/dto/AIModelDataDto.java
  src/main/java/com/gaebang/backend/domain/ai/dto/AIModelListResponseDto.java
  src/main/java/com/gaebang/backend/domain/ai/dto/AIUpdateNewsResponseDto.java
  src/main/java/com/gaebang/backend/domain/ai/dto/AiNewsResponseDto.java
  src/main/java/com/gaebang/backend/domain/ai/dto/OpenAiImageRequest.java
  src/main/java/com/gaebang/backend/domain/ai/entity/AIModelIntegrated.java
  src/main/java/com/gaebang/backend/domain/ai/entity/AiNews.java
  src/main/java/com/gaebang/backend/domain/ai/entity/AiUpdate.java
  src/main/java/com/gaebang/backend/domain/ai/exception/AINewsIsNotGeneratedException.java
  src/main/java/com/gaebang/backend/domain/ai/recommendation/Answers.java
  src/main/java/com/gaebang/backend/domain/ai/recommendation/Model.java
  src/main/java/com/gaebang/backend/domain/ai/recommendation/ModelScoreCalculator.java
  src/main/java/com/gaebang/backend/domain/ai/recommendation/Weights.java
  src/main/java/com/gaebang/backend/domain/ai/repository/AIAnalysisRepository.java
  src/main/java/com/gaebang/backend/domain/ai/repository/AiNewsRepository.java
  src/main/java/com/gaebang/backend/domain/ai/repository/AiUpdateRepository.java
  src/main/java/com/gaebang/backend/domain/ai/service/AIAnalysisService.java
  src/main/java/com/gaebang/backend/domain/ai/service/AiNewsService.java
  src/main/java/com/gaebang/backend/domain/ai/service/AiUpdatesService.java
  src/main/java/com/gaebang/backend/domain/ai/service/RecommendationService.java
  src/main/java/com/gaebang/backend/global/exception/ErrorCode.java
  src/main/java/com/gaebang/backend/global/springsecurity/SpringSecurityConfig.java
  src/main/java/com/gaebang/backend/global/util/S3/Base64DecodedMultipartFile.java
  src/test/java/com/morningstar/backend/http/AI/analysis.http
Labels: feat

#106 fix: 문서 파싱 시스템 10개 필드 지원 및 토큰 한도 최적화
  src/main/java/com/gaebang/backend/domain/interview/llm/GeminiInterviewerGateway.java
  src/main/java/com/gaebang/backend/domain/interview/service/DocumentContentExtractor.java
Labels: fix

#110 feat: 이미지 검열 시스템 구현
  build.gradle
  src/main/java/com/gaebang/backend/domain/community/dto/ModerationResult.java
  src/main/java/com/gaebang/backend/domain/community/entity/Board.java
  src/main/java/com/gaebang/backend/domain/community/entity/BoardBackup.java
  src/main/java/com/gaebang/backend/domain/community/entity/Comment.java
  src/main/java/com/gaebang/backend/domain/community/entity/CommentBackup.java
  src/main/java/com/gaebang/backend/domain/community/entity/ModerationStatus.java
  src/main/java/com/gaebang/backend/domain/community/exception/PostRateLimitExceededException.java
  src/main/java/com/gaebang/backend/domain/community/repository/BoardBackupRepository.java
  src/main/java/com/gaebang/backend/domain/community/repository/BoardRepository.java
  src/main/java/com/gaebang/backend/domain/community/repository/CommentBackupRepository.java
  src/main/java/com/gaebang/backend/domain/community/service/BoardService.java
  src/main/java/com/gaebang/backend/domain/community/service/CommentService.java
  src/main/java/com/gaebang/backend/domain/community/service/ContentBackupService.java
  src/main/java/com/gaebang/backend/domain/community/service/ImageModerationService.java
  src/main/java/com/gaebang/backend/domain/community/service/ModerationService.java
  src/main/java/com/gaebang/backend/domain/community/service/PostRateLimitService.java
  src/main/java/com/gaebang/backend/domain/community/service/TextModerationService.java
  src/main/java/com/gaebang/backend/domain/interview/llm/GeminiInterviewerGateway.java
  src/main/java/com/gaebang/backend/domain/interview/llm/OpenAiInterviewerGateway.java
  src/main/java/com/gaebang/backend/global/config/AsyncConfig.java
  src/main/java/com/gaebang/backend/global/exception/ErrorCode.java
  src/main/java/com/gaebang/backend/global/util/S3/S3ImageService.java
  src/main/resources/application-core.yml
  src/main/resources/application.yml
  src/test/java/com/morningstar/backend/MorningstarBackApplicationTests.java
Labels: feat

#115 fix: 검열 시스템 트랜잭션 문제 해결 및 보안 강화 완료
  build.gradle
  src/main/java/com/gaebang/backend/domain/community/event/BoardCreatedEvent.java
  src/main/java/com/gaebang/backend/domain/community/event/BoardUpdatedEvent.java
  src/main/java/com/gaebang/backend/domain/community/event/CommentCreatedEvent.java
  src/main/java/com/gaebang/backend/domain/community/event/CommentUpdatedEvent.java
  src/main/java/com/gaebang/backend/domain/community/listener/ModerationEventListener.java
  src/main/java/com/gaebang/backend/domain/community/service/BoardService.java
  src/main/java/com/gaebang/backend/domain/community/service/CommentService.java
  src/main/java/com/gaebang/backend/domain/community/service/ImageModerationService.java
  src/main/java/com/gaebang/backend/domain/community/service/ModerationService.java
  src/main/java/com/gaebang/backend/domain/community/service/TextModerationService.java
  src/main/java/com/gaebang/backend/domain/interview/llm/GeminiInterviewerGateway.java
  src/main/java/com/gaebang/backend/domain/interview/llm/OpenAiInterviewerGateway.java
  src/main/java/com/gaebang/backend/global/config/AsyncConfig.java
Labels: fix

#123 fix : 커넥션 풀 관련 설정 수정
  src/main/resources/application-prod.yml
Labels: fix

#125 refactor: 데이터베이스 엔티티 구조 개선
  src/main/java/com/gaebang/backend/domain/community/entity/BoardLike.java
  src/main/java/com/gaebang/backend/domain/interview/entity/InterviewAnswer.java
  src/main/java/com/gaebang/backend/domain/interview/entity/InterviewSession.java
Labels: refactor

#126 fix: BoardReport 엔티티 JoinColumn 매핑 수정
  src/main/java/com/gaebang/backend/domain/community/entity/BoardReport.java
Labels: fix

#134 fix: 엔티티-테이블명 불일치 수정
  .github/workflows/gradle.yml
  src/main/java/com/gaebang/backend/domain/interview/entity/InterviewAnswer.java
  src/main/java/com/gaebang/backend/domain/interview/entity/InterviewSession.java
Labels: fix

#141 fix : 기사 생성 시간 수정
  src/main/java/com/gaebang/backend/domain/ai/service/AiUpdatesService.java
Labels: fix

#145 feat: 게시글 목록 및 상세조회 API에 카테고리 응답 추가
  src/main/java/com/gaebang/backend/domain/community/dto/reqeust/BoardCreateAndEditRequestDto.java
  src/main/java/com/gaebang/backend/domain/community/dto/response/BoardDetailResponseDto.java
  src/main/java/com/gaebang/backend/domain/community/dto/response/BoardListProjectionDto.java
  src/main/java/com/gaebang/backend/domain/community/dto/response/BoardListResponseDto.java
  src/main/java/com/gaebang/backend/domain/community/entity/Board.java
  src/main/java/com/gaebang/backend/domain/community/entity/BoardCategory.java
  src/main/java/com/gaebang/backend/domain/community/repository/BoardRepository.java
  src/main/java/com/gaebang/backend/domain/community/service/BoardService.java
  src/main/java/com/gaebang/backend/global/config/AiMemberInitializer.java
Labels: feat
